-- ============================================================
-- Enterprise E-commerce Automation Framework
-- Oracle Source Schema
-- ============================================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SRC_CUSTOMER_ADDRESS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SRC_CUSTOMER CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE SRC_CUSTOMER (
    CUSTOMER_ID       NUMBER(10) PRIMARY KEY,
    SOURCE_SYSTEM     VARCHAR2(30) DEFAULT 'ORACLE_ECOM' NOT NULL,
    FIRST_NAME        VARCHAR2(50) NOT NULL,
    LAST_NAME         VARCHAR2(50) NOT NULL,
    EMAIL_ADDRESS     VARCHAR2(120),
    PHONE_NUMBER      VARCHAR2(20),
    DATE_OF_BIRTH     DATE,
    GENDER            VARCHAR2(10),
    CUSTOMER_STATUS   VARCHAR2(20) DEFAULT 'ACTIVE',
    CREATED_DATE      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE      TIMESTAMP,
    ETL_STATUS        VARCHAR2(20) DEFAULT 'PENDING',

    CONSTRAINT CHK_SRC_CUSTOMER_STATUS
        CHECK (CUSTOMER_STATUS IN ('ACTIVE', 'INACTIVE', 'BLOCKED')),

    CONSTRAINT CHK_SRC_CUSTOMER_GENDER
        CHECK (GENDER IN ('MALE', 'FEMALE', 'OTHER'))
);

CREATE TABLE SRC_CUSTOMER_ADDRESS (
    ADDRESS_ID        NUMBER(10) PRIMARY KEY,
    CUSTOMER_ID       NUMBER(10) NOT NULL,
    ADDRESS_TYPE      VARCHAR2(20) DEFAULT 'HOME',
    ADDRESS_LINE_1    VARCHAR2(150) NOT NULL,
    ADDRESS_LINE_2    VARCHAR2(150),
    CITY              VARCHAR2(80) NOT NULL,
    STATE_NAME        VARCHAR2(80),
    POSTAL_CODE       VARCHAR2(20),
    COUNTRY_NAME      VARCHAR2(80) DEFAULT 'INDIA',
    IS_PRIMARY        CHAR(1) DEFAULT 'Y',
    CREATED_DATE      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_SRC_ADDRESS_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES SRC_CUSTOMER(CUSTOMER_ID),

    CONSTRAINT CHK_SRC_ADDRESS_TYPE
        CHECK (ADDRESS_TYPE IN ('HOME', 'OFFICE', 'SHIPPING', 'BILLING')),

    CONSTRAINT CHK_SRC_ADDRESS_PRIMARY
        CHECK (IS_PRIMARY IN ('Y', 'N'))
);

CREATE INDEX IDX_SRC_CUSTOMER_EMAIL
    ON SRC_CUSTOMER(EMAIL_ADDRESS);

CREATE INDEX IDX_SRC_CUSTOMER_PHONE
    ON SRC_CUSTOMER(PHONE_NUMBER);

CREATE INDEX IDX_SRC_ADDRESS_CUSTOMER
    ON SRC_CUSTOMER_ADDRESS(CUSTOMER_ID);

COMMIT;